source "http://rubygems.org"

gem "sinatra"
gem "haml"
gem "sass"
gem "activesupport"
gem "datamapper", ">= 1.1.0"
gem "dm-mysql-adapter"
gem "redis"
gem "rest-client"
gem "nokogiri"
gem "proudhon", :git => 'git://github.com/Gargron/proudhon.git'
gem "sinatra-jsonp"
gem "sinatra-session"
gem "sinatra-flash"
gem "sinatra-redirect-with-flash"
gem "will_paginate"
gem "rack-flash"
gem "bcrypt-ruby", ">= 2.1.4"
gem "dm-paperclip"
gem "oembed_links"
gem "stalker"
gem "redcarpet"