source "http://rubygems.org"

gem "sinatra"
gem "haml"
gem "activesupport"
gem "datamapper", ">= 1.1.0"
gem "dm-mysql-adapter"
gem "redis"
gem "rdiscount"
gem "proudhon"
gem "sinatra-jsonp"
gem "sinatra-session"
gem "sinatra-flash"
gem "sinatra-redirect-with-flash"
gem "will_paginate"
gem "rspec"
gem "rack-flash"
gem "bcrypt-ruby", ">= 2.1.4"
gem "dm-paperclip"
gem "oembed_links"